### PR TITLE
Explain F-Droid AF

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by rouzbehzarei** [comment]
Why is it mentioned that the network service is non-free? Isn't that misleading? Users are not required to pay at all 🤔

**Comment by licaon-kter** [comment]
Read the rest of the text :)

**Comment by rouzbehzarei** [comment]
[Riseup VPN:](https://f-droid.org/en/packages/se.leap.riseupvpn/)

> By encrypting and securely routing all your network traffic through Riseup’s
> servers, RiseupVPN is able to prevent many forms of censorship and surveillance.

[Tusky:](https://f-droid.org/en/packages/com.keylesspalace.tusky/)

> Tusky is a lightweight client for Mastodon, a free and open-source social network server.

The apps above both depend on another service to function and are live on F-Droid but don't contain an AntiFeature explanation. What makes my app to differ?!

**Comment by licaon-kter** [comment]
Tusky is not tied to one particular server.

Riseup? Well... I tried: https://gitlab.com/fdroid/fdroiddata/-/issues/553#note_565181896

Yes, NonFreeNet needs a split, as the link above explains.

FYI, the app would get an AF anyway, if one can't change the server.

**Comment by rouzbehzarei** [comment]
I would like to use the same template as [Odysee](https://f-droid.org/en/packages/com.odysee.floss/), which is a separate section to warn users about the antifeature instead of mentioning it in middle of the [description](https://github.com/OdyseeTeam/odysee-android-floss/blob/main/fastlane/metadata/android/en-US/full_description.txt).

**Comment by licaon-kter** [comment]
:) https://github.com/OdyseeTeam/odysee-android-floss/pull/7/files

That being said, in your link you are seeing the footer of the website, that's standard for all apps that have an antifeature (or more).

This PR (and the one for Odysee) are adding a courtesy text to explain WHY. We usually didn't bother with that but users were coming and wondering _"how com nonfree when the marketing says foss"_.

As said elsewhere and other times, the AFs are not there to punish the devs but to inform the users. F-Droid is in the middle between these two parties, and each one feels that they kinda got betrayed if the AF appears or not.

**Comment by rouzbehzarei** [comment]
Please confirm [my commit](https://github.com/rouzbehzarei/filester/pull/14/commits/58deaebc180f0b7c52e465756d395c4ac7b07cbe) does not violate the terms so I can merge. The change is to explain "why" instead of restating the antifeature statement in the footer.

**Comment by licaon-kter** [comment]
Yup, sounds fine :)

**Pull request merged**
