### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As discussed in your [RFP at F--Droid](https://gitlab.com/fdroid/rfp/-/issues/2110), here's a little Fastlane starter package for you. After merging, be welcome to build on it – especially some screenshots would be very welcome. For some guidance, there are

* my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)
* my [hints on formatting `full_description.txt`](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) to best fit all places it can be used

If there are any questions, I try to answer them if I can.

### CODE REVIEW

**Review by rouzbehzarei — APPROVED** [review]
Thanks for the help :)

**Comment by IzzySoft** [comment]
Gladly – though your updates now broke some of the carefully drafted formatting :wink: But it's of course your decision how it should look like :smile:

I'll now enable Fastlane-pulling for your app in my repo, so when you release a new version it will be checked and pulled along. You left the "Markdown style" intact, so I'll set it to be rendered as Markdown – which will nicely format the paragraph as paragraph and the bullet-point list as proper list. F-Droid will take it as-is, just replace each `\n` (new-line) with a `<br>` (which is why paragraphs should be kept in one line, so the text "flows").

I see you already added screenshots and even per-release changelogs, wonderful! So I'll enable those as well and trigger an initial pull – that update of yours makes it definitely worth it :smile: Which means, your work will be reflected with the next sync around 6 pm UTC today.

Ouch, you broke the bullet-point list. Please don't use graphical bullet points, else it becomes a single paragraph with dots inside. Can you revert that please? Else I'd have to render the description as plain-text, which will not look as good. I've done this change locally on my end now one time, but I won't repeat that with future updates – so if you leave the graphical points as you have them now, the list will be broken with the next update. Take a look at the "formatting hints" link I gave you above for details :wink:

**Comment by rouzbehzarei** [comment]
I reverted the bullet list to follow the Markdown formatting again. I hope I got everything right this time. Again, appreciate the time you put into the details 🙏

**Comment by IzzySoft** [comment]
Looks good now, thanks a lot! Our issuebot just confirmed, so I'll mark the RFP "ready for packaging" now. Maybe you want to try a merge request on fdroiddata yourself? I'll set up an initial YAML you can use for that – with some luck it will work out-of-the-box.

PS: you should keep your `versionName` (currently `1.0`) and the tag name (`v1.0.0`) in sync with future releases – currently the tag name has an additional `.0`. Good point to start now, so fastlane will be picked up with the build: increase `versionCode` to `2`, update `versionName` to `1.0.1`, and tag `v1.0.1` maybe? If you do so, remember to adjust the values in my example YAML accordingly when trying the merge request :wink: You can then change `commit: v1.0.1` (I've set the commit hash currently to work around fastlane being not yet available at tag level).

**Comment by rouzbehzarei** [comment]
Ahh setting the `versionName` to `1.0` was definitely a rookie mistake! Ok I will take care of the merging as soon as I make a sense of what YAML is 😂 I'm a junior so I'll study that and do the merging then to avoid any mistakes. Will try to make it happen asap.

**Comment by IzzySoft** [comment]
Thanks @rouzbehzarei! That YAML is what F-Droid uses to define how an app is set up. Details can e.g. be found in the F-Droid documentation, see [Build Metadata Reference](https://f-droid.org/docs/Build_Metadata_Reference/). The YAML is what is merged to the fdroiddata repository at GitLab, telling the server software things like where to find the code, where to link to for issue trackers, what build recipe (and dependencies) to use, and some more.

I guess you could simply take the YAML I've set up in the RFP and use that with a merge request. Chances are good it will be a straight hit. If you plan to do so, please make sure to use a dedicated branch to open the merge request from (simply using `master` has some nasty side-effects). If you just state you prefer someone else does that, that's fine too – might take a little longer until someone of the team finds time to pick it up then.

As for `versionName`: quite a lot of "rookies" around here then :speak_no_evil: No worries, happens more often than you'd think :wink:

**Pull request merged**
